services:
    catalog:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/app
    postgres:
        image: postgres
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
volumes:
    postgres-data:
        driver: local
